### ISSUE TITLE
FisherExactTest(1,1,1,1) "Need extrema to return two distinct values"

### ISSUE THREAD

**Issue by jakkosdev** [JuliaStats/HypothesisTests.jl#245]
julia> HypothesisTests.FisherExactTest(1,1,1,1)
ERROR: ArgumentError: Need extrema to return two distinct values
Stacktrace:
  [1] _extrema
    @ ~/.julia/packages/Roots/H7pXT/src/utils.jl:43 [inlined]
  [2] find_zero(fs::Roots.FnWrapper, x0::Tuple{Float64, Float64}, method::Roots.Bisection; p::Nothing, tracks::Roots.NullTracks, verbose::Bool, kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Roots ~/.julia/packages/Roots/H7pXT/src/bracketing.jl:266
  [3] find_zero
    @ ~/.julia/packages/Roots/H7pXT/src/bracketing.jl:258 [inlined]
  [4] #fzero#97
    @ ~/.julia/packages/Roots/H7pXT/src/fzero.jl:85 [inlined]
  [5] fzero
    @ ~/.julia/packages/Roots/H7pXT/src/fzero.jl:81 [inlined]
  [6] #fzero#98
    @ ~/.julia/packages/Roots/H7pXT/src/fzero.jl:89 [inlined]
  [7] fzero
    @ ~/.julia/packages/Roots/H7pXT/src/fzero.jl:89 [inlined]
  [8] cond_mle_odds_ratio(a::Int64, b::Int64, c::Int64, d::Int64)
    @ HypothesisTests ~/.julia/packages/HypothesisTests/V7PST/src/fisher.jl:254
  [9] FisherExactTest(a::Int64, b::Int64, c::Int64, d::Int64)
    @ HypothesisTests ~/.julia/packages/HypothesisTests/V7PST/src/fisher.jl:71
 [10] top-level scope
    @ REPL[16]:1

**Comment by jakkosdev** [comment]
(@v1.6) pkg> status HypothesisTests
      Status `~/.julia/environments/v1.6/Project.toml`
  [09f84164] HypothesisTests v0.10.4

julia> VERSION
v"1.6.3"

**Comment by devmotion** [comment]
The problem is that the root finding algorithm in Roots is called with an empty bracket: both lower and upper value are the same which means it's not a proper bracket (the function evaluated at these points should return values of different signs). This seems to be a bug in `find_brackets` in https://github.com/JuliaStats/HypothesisTests.jl/blob/master/src/fisher.jl or we should check if the bracket is empty where the return value of `find_bracket` is used and not call into Roots in these cases.
